name: Propelty CI/CD prod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_DB: mydatabase
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U myuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Determine environment
        id: env
        run: |
          echo "env=prod" >> $GITHUB_ENV
          echo "tag=latest" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/myapp:${{ env.tag }} .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/myapp:${{ env.tag }}

#      - name: Deploy to server
#        run: |
#          ssh user@server "docker pull ghcr.io/${{ github.repository }}/myapp:${{ env.tag }} && docker-compose -f docker-compose.${{ env.env }}.yml up -d"
