name: Propelty CI/CD prod

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15.7-alpine
        env:
          POSTGRES_DB: "github-actions"
          POSTGRES_USER: "github-actions"
          POSTGRES_PASSWORD: "github-actions"
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U myuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          ls
          pip install -r ./apiserver/requirements.txt

      - name: Run migrations
        run: python ./apiserver/manage.py migrate

#      - name: Run tests
#        run: python ./apiserver/manage.py test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Determine environment
        id: env
        run: |
          echo "env=prod" >> $GITHUB_ENV
          echo "tag=latest" >> $GITHUB_ENV
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build and Push Space to Docker Hub
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./apiserver
          file: ./apiserver/Dockerfile.dev
          platforms: linux/amd64,linux/arm64
          tags: ${{ github.repository }}:${{ env.tag }}
          push: true

#      - name: Deploy to server
#        run: |
#          ssh user@server "docker pull ghcr.io/${{ github.repository }}/myapp:${{ env.tag }} && docker-compose -f docker-compose.${{ env.env }}.yml up -d"
